/*-
 * Copyright (c) 2011, Peter Tworek
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the author nor the names of any co-contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _PCF50633REG_H_
#define _PCF50633REG_H_

#define PCF50633_ADDR			0x73

/* On/Off Control */
#define PCF50633_VERSION		0x00
#define PCF50633_VARIANT		0x01
#define PCF50633_OOCSHDWN		0x0c
#define  OOCSHDWN_GO_STBY		(1<<0)
#define  OOCSHDWN_TOTRST		(1<<2)
#define  OOCSHDWN_COLDBOOT		(1<<3)
#define PCF50633_OOCWAKE		0x0d
#define  OOCWAKE_ONKEY_WAKE		(1<<0)
#define  OOCWAKE_EXTON1_WAKE		(1<<1)
#define  OOCWAKE_EXTON2_WAKE		(1<<2)
#define  OOCWAKE_EXTON3_WAKE		(1<<3)
#define  OOCWAKE_RTC_WAKE		(1<<4)
#define  OOCWAKE_USB_WAKE		(1<<5)
#define  OOCWAKE_ADP_WAKE		(1<<7)
#define PCF50633_OOCTIM1		0x0e
#define  OOCTIM1_EXTON1_DEB_MASK	(3<<0)
#define  OOCTIM1_EXTON1_DEB_0		(0<<0)
#define  OOCTIM1_EXTON1_DEB_5		(1<<0)
#define  OOCTIM1_EXTON1_DEB_14		(2<<0)
#define  OOCTIM1_EXTON1_DEB_62		(3<<0)
#define  OOCTIM1_EXTON2_DEB_MASK	(3<<2)
#define  OOCTIM1_EXTON2_DEB_0		(0<<2)
#define  OOCTIM1_EXTON2_DEB_5		(1<<2)
#define  OOCTIM1_EXTON2_DEB_14		(2<<2)
#define  OOCTIM1_EXTON2_DEB_62		(3<<2)
#define  OOCTIM1_EXTON3_DEB_MASK	(3<<4)
#define  OOCTIM1_EXTON3_DEB_0		(0<<4)
#define  OOCTIM1_EXTON3_DEB_5		(1<<4)
#define  OOCTIM1_EXTON3_DEB_14		(2<<4)
#define  OOCTIM1_EXTON3_DEB_62		(3<<4)
#define  OOCTIM1_SHDWN_DEB_MASK		(3<<6)
#define  OOCTIM1_SHDWN_DEB_0		(0<<6)
#define  OOCTIM1_SHDWN_DEB_5		(1<<6)
#define  OOCTIM1_SHDWN_DEB_14		(2<<6)
#define  OOCTIM1_SHDWN_DEB_62		(3<<6)
#define PCF50633_OOCTIM2		0x0f
#define  OOCTIM2_ONKEY_DEB_MASK		(7<<0)
#define  OOCTIM2_ONKEY_DEB_0		(0<<0)
#define  OOCTIM2_ONKEY_DEB_5		(1<<0)
#define  OOCTIM2_ONKEY_DEB_14		(2<<0)
#define  OOCTIM2_ONKEY_DEB_62		(3<<0)
#define  OOCTIM2_ONKEY_DEB_200		(4<<0)
#define  OOCTIM2_ONKEY_DEB_500		(5<<0)
#define  OOCTIM2_ONKEY_DEB_1k		(6<<0)
#define  OOCTIM2_ONKEY_DEB_2k		(7<<0)
#define  OOCTIM2_ACTPHDEL_MASK		(3<<3)
#define  OOCTIM2_ACTPHDEL_5		(0<<3)
#define  OOCTIM2_ACTPHDEL_10		(1<<3)
#define  OOCTIM2_ACTPHDEL_15		(2<<3)
#define  OOCTIM2_ACTPHDEL_20		(3<<3)
#define  OOCTIM2_HCRSTDEL_MASK		(3<<5)
#define  OOCTIM2_HCRSTDEL_3		(0<<5)
#define  OOCTIM2_HCRSTDEL_6		(1<<5)
#define  OOCTIM2_HCRSTDEL_13		(2<<5)
#define  OOCTIM2_HCRSTDEL_26		(3<<5)
#define  OOCTIM2_ALMON			(1<<7)
#define PCF50633_OOCMODE		0x10
#define  OOCMODE_EXTON1_MODE_MASK	(3<<0)
#define  OOCMODE_EXTON1_MODE_WAKE_F	(0<<0)
#define  OOCMODE_EXTON1_MODE_WAKE_R	(1<<0)
#define  OOCMODE_EXTON1_MODE_WAKE_FRTM	(2<<0)
#define  OOCMODE_EXTON1_MODE_WAKE_RFTM	(3<<0)
#define  OOCMODE_EXTON2_MODE_MASK	(3<<2)
#define  OOCMODE_EXTON2_MODE_WAKE_F	(0<<2)
#define  OOCMODE_EXTON2_MODE_WAKE_R	(1<<2)
#define  OOCMODE_EXTON2_MODE_WAKE_FRTM	(2<<2)
#define  OOCMODE_EXTON2_MODE_WAKE_RFTM	(3<<2)
#define  OOCMODE_EXTON3_MODE_MASK	(3<<4)
#define  OOCMODE_EXTON3_MODE_WAKE_F	(0<<4)
#define  OOCMODE_EXTON3_MODE_WAKE_R	(1<<4)
#define  OOCMODE_EXTON3_MODE_WAKE_FRTM	(2<<4)
#define  OOCMODE_EXTON3_MODE_WAKE_RFTM	(3<<4)
#define  OOCMODE_ONKEY_MODE_MASK	(3<<4)
#define  OOCMODE_ONKEY_MODE_WAKE_F	(0<<4)
#define  OOCMODE_ONKEY_MODE_WAKE_FTM	(1<<4)
#define  OOCMODE_ONKEY_MODE_WAKE_FRTM	(2<<4)
#define PCF50633_OOCCTL			0x11
#define  OOCCTL_ACTPHRST_MASK		(3<<0)
#define  OOCCTL_ACTPHRST_PHASE1		(0<<0)
#define  OOCCTL_ACTPHRST_PHASE2		(1<<0)
#define  OOCCTL_ACTPHRST_PHASE3		(2<<0)
#define  OOCCTL_ACTPHRST_PHASE4		(3<<0)
#define  OOCCTL_ACTPHRST_ACTCLK32ON	(1<<2)
#define  OOCCTL_HEARTBEAT		(1<<3)
#define  OOCCTL_USBBATCHK		(1<<4)
#define  OOCCTL_STBCLK32ON		(1<<6)
#define PCF50633_OOCSTAT		0x12
#define  OOCSTAT_ONKEY			(1<<0)
#define  OOCSTAT_EXTON1			(1<<1)
#define  OOCSTAT_EXTON2			(1<<2)
#define  OOCSTAT_EXTON3			(1<<3)
#define  OOCSTAT_BUBPRES		(1<<4)
#define  OOCSTAT_SYSOK			(1<<5)
#define  OOCSTAT_BATOK			(1<<6)
#define  OOCSTAT_TMPOK			(1<<7)

/* Interrupt controller */
#define PCF50633_INT_REG_N		5
#define PCF50633_INTRS_NO		(PCF50633_INT_REG_N*8)
#define PCF50633_INT1			0x02
#define  INT1_ADPINS_BIT		0
#define  INT1_ADPINS			(1<<INT1_ADPINS_BIT)
#define  INT1_ADPREM_BIT		1
#define  INT1_ADPREM			(1<<INT1_ADPREM_BIT)
#define  INT1_USBINS_BIT		2
#define  INT1_USBINS			(1<<INT1_USBINS_BIT)
#define  INT1_USBREM_BIT		3
#define  INT1_USBREM			(1<<INT1_USBREM_BIT)
#define  INT1_RTCALARM_BIT		6
#define  INT1_RTCALARM			(1<<INT1_USBREM_BIT)
#define  INT1_SECOND_BIT		7
#define  INT1_SECOND			(1<<INT_I_SECOND_BIT)
#define PCF50633_INT2			0x03
#define  INT2_ONKEYR_BIT		0
#define  INT2_ONKEYR			(1<<INT2_ONKEYR_BIT)
#define  INT2_ONKEYF_BIT		1
#define  INT2_ONKEYF			(1<<INT2_ONKEYF_BIT)
#define  INT2_EXTON1R_BIT		2
#define  INT2_EXTON1R			(1<<INT2_EXTON1R_BIT)
#define  INT2_EXTON1F_BIT		3
#define  INT2_EXTON1F			(1<<INT2_EXTON1F_BIT)
#define  INT2_EXTON2R_BIT		4
#define  INT2_EXTON2R			(1<<INT2_EXTON2R_BIT)
#define  INT2_EXTON2F_BIT		5
#define  INT2_EXTON2F			(1<<INT2_EXTON2F_BIT)
#define  INT2_EXTON3R_BIT		6
#define  INT2_EXTON3R			(1<<INT2_EXTON3R_BIT)
#define  INT2_EXTON3F_BIT		7
#define  INT2_EXTON3F			(1<<INT2_EXTON3F_BIT)
#define PCF50633_INT3			0x04
#define  INT3_BATFULL_BIT		0
#define  INT3_BATFULL			(1<<INT3_BATFULL_BIT)
#define  INT3_CHGHALT_BIT		1
#define  INT3_CHGHALT			(1<<INT3_CHGHALT_BIT)
#define  INT3_THLIMON_BIT		2
#define  INT3_THLIMON			(1<<INT3_THLIMON_BIT)
#define  INT3_THLIMOFF_BIT		3
#define  INT3_THLIMOFF			(1<<INT3_THLIMOFF_BIT)
#define  INT3_USBLIMON_BIT		4
#define  INT3_USBLIMON			(1<<INT3_USBLIMON_BIT)
#define  INT3_USBLIMOFF_BIT		5
#define  INT3_USBLIMOFF			(1<<INT3_USBLIMOFF_BIT)
#define  INT3_ADCRDY_BIT		6
#define  INT3_ADCRDY			(1<<INT3_ADCRDY_BIT)
#define  INT3_ONKEY1S_BIT		7
#define  INT3_ONKEY1S			(1<<INT3_ONKEY1S_BIT)
#define PCF50633_INT4			0x05
#define  INT4_LOWSYS_BIT		0
#define  INT4_LOWSYS			(1<<INT4_LOWSYS_BIT)
#define  INT4_LOWBAT_BIT		(1<<1)
#define  INT4_LOWBAT			(1<<INT4_LOWBAT_BIT)
#define  INT4_HIGHTMP_BIT		2
#define  INT4_HIGHTMP			(1<<INT4_HIGHTML_BIT)
#define  INT4_AUTOPWRFAIL_BIT		3
#define  INT4_AUTOPWRFAIL		(1<<INT4_AUTOPWRFAIL_BIT)
#define  INT4_DWN1PWRFAIL_BIT		4
#define  INT4_DWN1PWRFAIL		(1<<INT4_DWN1PWRFAIL_BIT)
#define  INT4_DWN2PWRFAIL_BIT		5
#define  INT4_DWN2PWRFAIL		(1<<INT4_DWN2PWRFAIL_BIT)
#define  INT4_LEDPWRFAIL_BIT		6
#define  INT4_LEDPWRFAIL		(1<<INT4_LEDPWRFAIL_BIT)
#define  INT4_LEDOVP_BIT		7
#define  INT4_LEDOVP			(1<<INT4_LEDOVP_BIT)
#define PCF50633_INT5			0x06
#define  INT5_LDO1PWRFAIL_BIT		0
#define  INT5_LDO1PWRFAIL		(1<<INT5_LDO1PWRFAIL_BIT)
#define  INT5_LDO2PWRFAIL_BIT		1
#define  INT5_LDO2PWRFAIL		(1<<INT5_LDO2PWRFAIL_BIT)
#define  INT5_LDO3PWRFAIL_BIT		2
#define  INT5_LDO3PWRFAIL		(1<<INT5_LDO3PWRFAIL_BIT)
#define  INT5_LDO4PWRFAIL_BIT		3
#define  INT5_LDO4PWRFAIL		(1<<INT5_LDO4PWRFAIL_BIT)
#define  INT5_LDO5PWRFAIL_BIT		4
#define  INT5_LDO5PWRFAIL		(1<<INT5_LDO5PWRFAIL_BIT)
#define  INT5_LDO6PWRFAIL_BIT		5
#define  INT5_LDO6PWRFAIL		(1<<INT5_LDO6PWRFAIL_BIT)
#define  INT5_HCLDOPWRFAIL_BIT		6
#define  INT5_HCLDOPWRFAIL		(1<<INT5_HCLDOPWRFAIL_BIT)
#define  INT5_HCLDOOVL_BIT		7
#define  INT5_HCLDOOVL			(1<<INT5_HCLDOOVL_BIT)
#define PCF50633_INT1MASK		0x07
#define PCF50633_INT2MASK		0x08
#define PCF50633_INT3MASK		0x09
#define PCF50633_INT4MASK		0x0a
#define PCF50633_INT5MASK		0x0b

/* Power Supply Module */
#define PCF50633_STBYCTL1		0x3b
#define  STBYCTL1_LDO1_ENA_SHIFT	0
#define  STBYCTL1_LDO1_ENA		(1<<STBYCTL1_LDO1_ENA_SHIFT)
#define  STBYCTL1_LDO2_ENA_SHIFT	2
#define  STBYCTL1_LDO2_ENA		(1<<STBYCTL1_LDO2_ENA_SHIFT)
#define  STBYCTL1_LDO3_ENA_SHIFT	4
#define  STBYCTL1_LDO3_ENA		(1<<STBYCTL1_LDO3_ENA_SHIFT)
#define  STBYCTL1_LDO4_ENA_SHIFT	6
#define  STBYCTL1_LDO4_ENA		(1<<STBYCTL1_LDO4_ENA_SHIFT)
#define PCF50633_STBYCTL2		0x3c
#define  STBYCTL2_LDO5_ENA_SHIFT	0
#define  STBYCTL2_LDO5_ENA		(1<<STBYCTL2_LDO5_ENA_SHIFT)
#define  STBYCTL2_LDO6_ENA_SHIFT	2
#define  STBYCTL2_LDO6_ENA		(1<<STBYCTL2_LDO6_ENA_SHIFT)
#define  STBYCTL2_HCLDO_ENA_SHIFT	4
#define  STBYCTL2_HCLDO_ENA		(1<<STBYCTL2_HCLDO_ENA_SHIFT)
#define  STBYCTL2_MEMLDO_ENA_SHIFT	6
#define  STBYCTL2_MEMLDO_ENA		(1<<STBYCTL2_MEMLDO_ENA_SHIFT)
#define PCF50633_DEBPF1			0x3d
#define  DEBPF1_AUTO_SHIFT		0
#define  DEBPF1_AUTO_MASK		(0x3<<DEBPF1_AUTO_SHIFT)
#define  DEBPF1_DOWN1_SHIFT		2
#define  DEBPF1_DOWN1_MASK		(0x3<<DEBPF1_DOWN1_SHIFT)
#define  DEBPF1_DOWN2_SHIFT		4
#define  DEBPF1_DOWN2_MASK		(0x3<<DEBPF1_DOWN2_SHIFT)
#define  DEBPF1_LED_SHIFT		6
#define  DEBPF1_LED_MASK		(0x3<<DEBPF1_LED_SHIFT)
#define PCF50633_DEBPF2			0x3e
#define  DEBPF2_LDO1_SHIFT		0
#define  DEBPF2_LDO1_MASK		(0x3<<DEBPF2_LDO1_SHIFT)
#define  DEBPF2_LDO2_SHIFT		2
#define  DEBPF2_LDO2_MASK		(0x3<<DEBPF2_LDO2_SHIFT)
#define  DEBPF2_LDO3_SHIFT		4
#define  DEBPF2_LDO3_MASK		(0x3<<DEBPF2_LDO3_SHIFT)
#define  DEBPF2_LDO4_SHIFT		6
#define  DEBPF2_LDO4_MASK		(0x3<<DEBPF2_LDO4_SHIFT)
#define PCF50633_DEBPF3			0x3f
#define  DEBPF3_LDO5_SHIFT		0
#define  DEBPF3_LDO5_MASK		(0x3<<DEBPF3_LDO5_SHIFT)
#define  DEBPF3_LDO6_SHIFT		2
#define  DEBPF3_LDO6_MASK		(0x3<<DEBPF3_LDO6_SHIFT)
#define  DEBPF3_HCLDO_SHIFT		4
#define  DEBPF3_HCLDO_MASK		(0x3<<DEBPF3_HCLDO_SHIFT)
#define PCF50633_DCDCSTAT		0x41
#define  DCDCSTAT_AUTO			(1<<0)
#define  DCDCSTAT_DOWN1			(1<<1)
#define  DCDCSTAT_DOWN2			(1<<2)
#define  DCDCSTAT_LED			(1<<3)
#define PCF50633_LDOSTAT		0x42
#define  LDOSTAT_LDO1			(1<<0)
#define  LDOSTAT_LDO2			(1<<1)
#define  LDOSTAT_LDO3			(1<<2)
#define  LDOSTAT_LDO4			(1<<3)
#define  LDOSTAT_LDO5			(1<<4)
#define  LDOSTAT_LDO6			(1<<5)
#define  LDOSTAT_HCLDO			(1<<6)
#define  LDOSTAT_HCLDO_OVL		(1<<7)

/* AUTO, DOWN1 and DOWN2 step-down converters */
#define PCF50633_AUTOOUT		0x1a
#define PCF50633_AUTOENA		0x1b
#define  AUTOENA_ACTPH_SHIFT		4
#define  AUTOENA_ACTPH_MASK		(0x3<<AUTOENA_ACTPH_SHIFT)
#define PCF50633_AUTOCTL		0x1c
#define  AUTOCTL_PWMONLY		0x1
#define  AUTOCTL_MOD_SHIFT		1
#define  AUTOCTL_MOD			(1<<1)
#define PCF50633_AUTOMXC		0x1d
#define  AUTOMXC_CURLIM_MASK		0x3f
#define  AUTOMXC_MODE_SHIFT		6
#define  AUTOMXC_MODE			(1<<AUTOMXC_MAXCMOD_SHIFT)
#define PCF50633_DOWN1OUT		0x1e
#define PCF50633_DOWN1ENA		0x1f
#define  DOWN1ENA_ACTPH_SHIFT		4
#define  DOWN1ENA_ACTPH_MASK		(0x3<<DOWN1ENA_ACTPH_SHIFT)
#define PCF50633_DOWN1CTL		0x20
#define  DOWN1CTL_PWMONLY		0x1
#define  DOWN1CTL_DVMSTEP_SHIFT		1
#define  DOWN1CTL_DVMSTEP_MASK		(0xf<<DOWN1CTL_DVMSTEP_SHIFT)
#define PCF50633_DOWN1MXC		0x21
#define  DOWN1MXC_CURLIM_MASK		0x3f
#define  DOWN1MXC_MODE_SHIFT		6
#define  DOWN1MXC_MODE			(1<<DOWN1MXC_MODE_SHIFT)
#define PCF50633_DOWN2OUT		0x22
#define PCF50633_DOWN2ENA		0x23
#define  DOWN2ENA_ACTPH_SHIFT		4
#define  DOWN2ENA_ACTPH_MASK		(0x3<<DOWN2ENA_ACTPH_SHIFT)
#define PCF50633_DOWN2CTL		0x24
#define  DOWN2CTL_PWMONLY		0x1
#define  DOWN2CTL_DVMSTEP_SHIFT		1
#define  DOWN2CTL_DVMSTEP_MASK		(0xf<<DOWN2CTL_DVMSTEP_SHIFT)
#define PCF50633_DOWN2MXC		0x25
#define  DOWN2MXC_CURLIM_MASK		0x3f
#define  DOWN2MXC_MODE_SHIFT		6
#define  DOWN2MXC_MODE			(1<<DOWN2MXC_MODE_SHIFT)

/* Linear regulators */
#define PCF50633_MEMLDOOUT		0x26
#define PCF50633_MEMLDOENA		0x27
#define PCF50633_LDOxOUT(x)		(2*(x)+0x2d)
#define  LDOxOUT_SWMOD_SHIFT		5
#define  LDOxOUT_SWMOD			(1<<LDOxOUT_SWMOD_SHIFT)
#define PCF50633_LDOxENA(x)		(2*(x)+0x2e)
#define  LDOxENA_ACTPH_SHIFT		4
#define  LDOxENA_ACTPH_MASK		(3<<LDOxENA_ACTPH_SHIFT)

/* Real Time Clock */
#define PCF50633_RTC_REGS		7
#define PCF50633_REG_RTCSC		0x59
#define PCF50633_REG_RTCMN		0x5a
#define PCF50633_REG_RTCHR		0x5b
#define PCF50633_REG_RTCWD		0x5c
#define PCF50633_REG_RTCDT		0x5d
#define PCF50633_REG_RTCMT		0x5e
#define PCF50633_REG_RTCYR		0x5f

#define PCF50633_REG_RTCSCA		0x60
#define PCF50633_REG_RTCMNA		0x61
#define PCF50633_REG_RTCHRA		0x62
#define PCF50633_REG_RTCWDA		0x63
#define PCF50633_REG_RTCDTA		0x64
#define PCF50633_REG_RTCMTA		0x65
#define PCF50633_REG_RTCYRA		0x66

#endif /* !_PCF50633REG_H_ */
